import { BellRing, CreditCard, MailCheck, ShieldCheck, UserRoundCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { BankIdBadge } from "@/components/MarketplaceBits";
import { fetchEmailTemplates } from "@/lib/api";

export default function ProfilePage() {
  const [templates, setTemplates] = useState([]);
  useEffect(() => { fetchEmailTemplates().then(setTemplates).catch(() => setTemplates([])); }, []);
  return <div className="page profile-page" data-testid="profile-page"><section className="page-intro compact"><div><p className="eyebrow">MIN PROFIL</p><h1>Trygg fra første klikk.</h1><p>Profil, varsler og integrasjoner er samlet på ett sted.</p></div></section><section className="profile-grid"><div className="profile-card" data-testid="customer-profile-card"><div className="large-avatar">KJ</div><div><h2>Kari Johansen</h2><p>Kunde · Oslo</p><BankIdBadge /></div><button type="button" className="secondary-button" data-testid="edit-profile-button">Rediger profil</button></div><div className="verification-card" data-testid="bankid-verification-card"><ShieldCheck size={28} /><div><p className="eyebrow">IDENTITET</p><h2>BankID-verifisert</h2><p>Navn og identitet er bekreftet. Full integrasjon aktiveres når Criipto er koblet til.</p></div><span className="status-ready">Klar</span></div></section><section className="settings-grid"><div className="settings-block" data-testid="payment-settings"><CreditCard size={21} /><div><p className="eyebrow">BETALING</p><h2>Stripe og Vipps</h2><p>Håndverkere legger til betalingsmetode under onboarding. Oppdragstildeling er klar for automatisk trekk.</p><span className="integration-status" data-testid="payment-integration-status">Venter på tilganger</span></div></div><div className="settings-block" data-testid="notification-settings"><BellRing size={21} /><div><p className="eyebrow">VARSER</p><h2>Smartere oppfølging</h2><p>Du mottar varsler for nye tilbud, tildeling og ratingpåminnelser.</p><button className="text-button" type="button" data-testid="notification-settings-button">Administrer varsler</button></div></div></section><section className="email-section" data-testid="email-templates-section"><div className="section-heading"><div><p className="eyebrow">E-POSTAUTOMATISERING</p><h2>Klare meldingsløp</h2></div><MailCheck size={23} /></div><div className="template-grid">{templates.map((template) => <div className="template-item" key={template.id} data-testid={`email-template-${template.id}`}><UserRoundCheck size={18} /><div><h3>{template.title}</h3><p>{template.trigger}</p></div><span>Aktiveres ved oppsett</span></div>)}</div></section></div>;
}