
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


import AdPreviewPage from "./pages/AdPreviewPage.tsx";
import AdminDashboardPage from "./pages/AdminDashboardPage.tsx";
import App from "./pages/App.tsx";
import AssignmentDetailsPage from "./pages/AssignmentDetailsPage.tsx";
import BankidCallbackPage from "./pages/BankidCallbackPage.tsx";
import ContactUsPage from "./pages/ContactUsPage.tsx";
import CraftsmanDashboard from "./pages/CraftsmanDashboard.tsx";
import CraftsmanProfilePage from "./pages/CraftsmanProfilePage.tsx";
import EditCraftsmanProfile from "./pages/EditCraftsmanProfile.tsx";
import EditProfile from "./pages/EditProfile.tsx";
import FindCraftsmen from "./pages/FindCraftsmen.tsx";
import ForHandverkerePage from "./pages/ForHandverkerePage.tsx";
import HandverkerRegistrering from "./pages/HandverkerRegistrering.tsx";
import LaunchInfoPage from "./pages/LaunchInfoPage.tsx";
import MyAssignmentsPage from "./pages/MyAssignmentsPage.tsx";
import MyLeadsPage from "./pages/MyLeadsPage.tsx";
import PaymentCanceledPage from "./pages/PaymentCanceledPage.tsx";
import PaymentSuccessPage from "./pages/PaymentSuccessPage.tsx";
import PrivacyPolicyPage from "./pages/PrivacyPolicyPage.tsx";
import PurchaseLeadsPage from "./pages/PurchaseLeadsPage.tsx";
import ServiceRequestPage from "./pages/ServiceRequestPage.tsx";
import TermsOfServicePage from "./pages/TermsOfServicePage.tsx";

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect /> },
	{ path: "/auth/*", element: <StackHandlerRoutes /> },
	{ path: "/ad-preview-page", element: <AdPreviewPage /> },
	{ path: "/adpreviewpage", element: <AdPreviewPage /> },
	{ path: "/admin-dashboard-page", element: <AdminDashboardPage /> },
	{ path: "/admindashboardpage", element: <AdminDashboardPage /> },
	{ path: "/", element: <App /> },
	{ path: "/assignment-details-page", element: <UserGuard><AssignmentDetailsPage /></UserGuard> },
	{ path: "/assignmentdetailspage", element: <UserGuard><AssignmentDetailsPage /></UserGuard> },
	{ path: "/bankid-callback-page", element: <UserGuard><BankidCallbackPage /></UserGuard> },
	{ path: "/bankidcallbackpage", element: <UserGuard><BankidCallbackPage /></UserGuard> },
	{ path: "/contact-us-page", element: <ContactUsPage /> },
	{ path: "/contactuspage", element: <ContactUsPage /> },
	{ path: "/craftsman-dashboard", element: <UserGuard><CraftsmanDashboard /></UserGuard> },
	{ path: "/craftsmandashboard", element: <UserGuard><CraftsmanDashboard /></UserGuard> },
	{ path: "/craftsman-profile-page", element: <CraftsmanProfilePage /> },
	{ path: "/craftsmanprofilepage", element: <CraftsmanProfilePage /> },
	{ path: "/edit-craftsman-profile", element: <UserGuard><EditCraftsmanProfile /></UserGuard> },
	{ path: "/editcraftsmanprofile", element: <UserGuard><EditCraftsmanProfile /></UserGuard> },
	{ path: "/edit-profile", element: <UserGuard><EditProfile /></UserGuard> },
	{ path: "/editprofile", element: <UserGuard><EditProfile /></UserGuard> },
	{ path: "/find-craftsmen", element: <FindCraftsmen /> },
	{ path: "/findcraftsmen", element: <FindCraftsmen /> },
	{ path: "/for-handverkere-page", element: <ForHandverkerePage /> },
	{ path: "/forhandverkerepage", element: <ForHandverkerePage /> },
	{ path: "/handverker-registrering", element: <UserGuard><HandverkerRegistrering /></UserGuard> },
	{ path: "/handverkerregistrering", element: <UserGuard><HandverkerRegistrering /></UserGuard> },
	{ path: "/launch-info-page", element: <LaunchInfoPage /> },
	{ path: "/launchinfopage", element: <LaunchInfoPage /> },
	{ path: "/my-assignments-page", element: <UserGuard><MyAssignmentsPage /></UserGuard> },
	{ path: "/myassignmentspage", element: <UserGuard><MyAssignmentsPage /></UserGuard> },
	{ path: "/my-leads-page", element: <UserGuard><MyLeadsPage /></UserGuard> },
	{ path: "/myleadspage", element: <UserGuard><MyLeadsPage /></UserGuard> },
	{ path: "/payment-canceled-page", element: <PaymentCanceledPage /> },
	{ path: "/paymentcanceledpage", element: <PaymentCanceledPage /> },
	{ path: "/payment-success-page", element: <UserGuard><PaymentSuccessPage /></UserGuard> },
	{ path: "/paymentsuccesspage", element: <UserGuard><PaymentSuccessPage /></UserGuard> },
	{ path: "/privacy-policy-page", element: <PrivacyPolicyPage /> },
	{ path: "/privacypolicypage", element: <PrivacyPolicyPage /> },
	{ path: "/purchase-leads-page", element: <UserGuard><PurchaseLeadsPage /></UserGuard> },
	{ path: "/purchaseleadspage", element: <UserGuard><PurchaseLeadsPage /></UserGuard> },
	{ path: "/service-request-page", element: <UserGuard><ServiceRequestPage /></UserGuard> },
	{ path: "/servicerequestpage", element: <UserGuard><ServiceRequestPage /></UserGuard> },
	{ path: "/terms-of-service-page", element: <TermsOfServicePage /> },
	{ path: "/termsofservicepage", element: <TermsOfServicePage /> },

];
