// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("../pages/App.tsx"));
const AssignmentDetailsPage = lazy(() => import("../pages/AssignmentDetailsPage.tsx"));
const CallPage = lazy(() => import("../pages/CallPage.tsx"));
const ContactUsPage = lazy(() => import("../pages/ContactUsPage.tsx"));
const CraftsmanDashboard = lazy(() => import("../pages/CraftsmanDashboard.tsx"));
const CraftsmanProfile = lazy(() => import("../pages/CraftsmanProfile.tsx"));
const CraftsmanProfileEdit = lazy(() => import("../pages/CraftsmanProfileEdit.tsx"));
const CraftsmanRegistration = lazy(() => import("../pages/CraftsmanRegistration.tsx"));
const CustomerDashboard = lazy(() => import("../pages/CustomerDashboard.tsx"));
const EditCraftsmanProfile = lazy(() => import("../pages/EditCraftsmanProfile.tsx"));
const EditProfile = lazy(() => import("../pages/EditProfile.tsx"));
const FindCraftsmen = lazy(() => import("../pages/FindCraftsmen.tsx"));
const MyAssignments = lazy(() => import("../pages/MyAssignments.tsx"));
const MyAssignmentsPage = lazy(() => import("../pages/MyAssignmentsPage.tsx"));
const MyLeadsPage = lazy(() => import("../pages/MyLeadsPage.tsx"));
const PaymentCanceledPage = lazy(() => import("../pages/PaymentCanceledPage.tsx"));
const PaymentSuccessPage = lazy(() => import("../pages/PaymentSuccessPage.tsx"));
const PrivacyPolicyPage = lazy(() => import("../pages/PrivacyPolicyPage.tsx"));
const PurchaseLeadsPage = lazy(() => import("../pages/PurchaseLeadsPage.tsx"));
const ServiceRequest = lazy(() => import("../pages/ServiceRequest.tsx"));
const ServiceRequestPage = lazy(() => import("../pages/ServiceRequestPage.tsx"));
const TermsOfServicePage = lazy(() => import("../pages/TermsOfServicePage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/assignment-details-page", element: <UserGuard><AssignmentDetailsPage /></UserGuard>},
	{ path: "/assignmentdetailspage", element: <UserGuard><AssignmentDetailsPage /></UserGuard>},
	{ path: "/call-page", element: <UserGuard><CallPage /></UserGuard>},
	{ path: "/callpage", element: <UserGuard><CallPage /></UserGuard>},
	{ path: "/contact-us-page", element: <UserGuard><ContactUsPage /></UserGuard>},
	{ path: "/contactuspage", element: <UserGuard><ContactUsPage /></UserGuard>},
	{ path: "/craftsman-dashboard", element: <UserGuard><CraftsmanDashboard /></UserGuard>},
	{ path: "/craftsmandashboard", element: <UserGuard><CraftsmanDashboard /></UserGuard>},
	{ path: "/craftsman-profile/:craftsmanId", element: <UserGuard><CraftsmanProfile /></UserGuard>},
	{ path: "/craftsmanprofile/:craftsmanId", element: <UserGuard><CraftsmanProfile /></UserGuard>},
	{ path: "/craftsman-profile-edit", element: <UserGuard><CraftsmanProfileEdit /></UserGuard>},
	{ path: "/craftsmanprofileedit", element: <UserGuard><CraftsmanProfileEdit /></UserGuard>},
	{ path: "/craftsman-registration", element: <UserGuard><CraftsmanRegistration /></UserGuard>},
	{ path: "/craftsmanregistration", element: <UserGuard><CraftsmanRegistration /></UserGuard>},
	{ path: "/customer-dashboard", element: <UserGuard><CustomerDashboard /></UserGuard>},
	{ path: "/customerdashboard", element: <UserGuard><CustomerDashboard /></UserGuard>},
	{ path: "/edit-craftsman-profile", element: <UserGuard><EditCraftsmanProfile /></UserGuard>},
	{ path: "/editcraftsmanprofile", element: <UserGuard><EditCraftsmanProfile /></UserGuard>},
	{ path: "/edit-profile", element: <UserGuard><EditProfile /></UserGuard>},
	{ path: "/editprofile", element: <UserGuard><EditProfile /></UserGuard>},
	{ path: "/find-craftsmen", element: <UserGuard><FindCraftsmen /></UserGuard>},
	{ path: "/findcraftsmen", element: <UserGuard><FindCraftsmen /></UserGuard>},
	{ path: "/my-assignments", element: <UserGuard><MyAssignments /></UserGuard>},
	{ path: "/myassignments", element: <UserGuard><MyAssignments /></UserGuard>},
	{ path: "/my-assignments-page", element: <UserGuard><MyAssignmentsPage /></UserGuard>},
	{ path: "/myassignmentspage", element: <UserGuard><MyAssignmentsPage /></UserGuard>},
	{ path: "/my-leads-page", element: <UserGuard><MyLeadsPage /></UserGuard>},
	{ path: "/myleadspage", element: <UserGuard><MyLeadsPage /></UserGuard>},
	{ path: "/payment-canceled-page", element: <UserGuard><PaymentCanceledPage /></UserGuard>},
	{ path: "/paymentcanceledpage", element: <UserGuard><PaymentCanceledPage /></UserGuard>},
	{ path: "/payment-success-page", element: <UserGuard><PaymentSuccessPage /></UserGuard>},
	{ path: "/paymentsuccesspage", element: <UserGuard><PaymentSuccessPage /></UserGuard>},
	{ path: "/privacy-policy-page", element: <UserGuard><PrivacyPolicyPage /></UserGuard>},
	{ path: "/privacypolicypage", element: <UserGuard><PrivacyPolicyPage /></UserGuard>},
	{ path: "/purchase-leads-page", element: <UserGuard><PurchaseLeadsPage /></UserGuard>},
	{ path: "/purchaseleadspage", element: <UserGuard><PurchaseLeadsPage /></UserGuard>},
	{ path: "/service-request", element: <UserGuard><ServiceRequest /></UserGuard>},
	{ path: "/servicerequest", element: <UserGuard><ServiceRequest /></UserGuard>},
	{ path: "/service-request-page", element: <UserGuard><ServiceRequestPage /></UserGuard>},
	{ path: "/servicerequestpage", element: <UserGuard><ServiceRequestPage /></UserGuard>},
	{ path: "/terms-of-service-page", element: <UserGuard><TermsOfServicePage /></UserGuard>},
	{ path: "/termsofservicepage", element: <UserGuard><TermsOfServicePage /></UserGuard>},

];
